### ISSUE TITLE
Problem with attributes 

### ISSUE THREAD

**Issue by Webmasterei** [Vinai/nicer-image-names#25]
Hi great extension! Saved me a lot of headache!
I habe a little problem though.
When I have an attribute like %product_type it does not work, as $product is beeing taken as variable and _type as a plain string. How to work around this?

**Comment by Vinai** [comment]
Two things have to be considered.
First, attributes with underscores in their name need to be written in camel case, e.g. `%productType`.
When matching those attributes it still could happen that it matches an attribute as `%product`, if such an attribute is present.
In those cases you can force the full name to be used by enclosing the name in curly braces: `%{productType}`.

**Comment by Webmasterei** [comment]
That worked! Thanks.
